project_id = "alzndmtpyvtsnsnwzipb"

[functions.generate-questions]
verify_jwt = false

[functions.topic-chat]
verify_jwt = false

[functions.interview-hr]
verify_jwt = false

[functions.coding-problem]
verify_jwt = false

[functions.evaluate-code]
verify_jwt = false

[functions.company-placement-test]
verify_jwt = false

[functions.faculty-ai-insights]
verify_jwt = false
